services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # SECURITY
    #

    OpenDxp\Bundle\AdminBundle\EventListener\AdminSecurityListener: ~

    OpenDxp\Bundle\AdminBundle\EventListener\CsrfProtectionListener: ~

    #
    # EXCEPTION HANDLING
    #

    OpenDxp\Bundle\AdminBundle\EventListener\AdminExceptionListener: ~

    #
    # GRID CONFIG CLEANUP
    #

    OpenDxp\Bundle\AdminBundle\EventListener\GridConfigListener: ~

    #
    # IMPORT CONFIG CLEANUP
    #

    OpenDxp\Bundle\AdminBundle\EventListener\ImportConfigListener: ~

    #
    # MISC
    #

    OpenDxp\Bundle\AdminBundle\EventListener\AdminSessionBagListener: ~

    OpenDxp\Bundle\AdminBundle\EventListener\HttpCacheListener: ~

    OpenDxp\Bundle\AdminBundle\EventListener\CustomAdminEntryPointCheckListener:
        arguments: ['%opendxp_admin.custom_admin_path_identifier%']

    OpenDxp\Bundle\AdminBundle\EventListener\UserPerspectiveListener:
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: monolog.logger, channel: admin }

    OpenDxp\Bundle\AdminBundle\EventListener\UsageStatisticsListener:
        calls:
            - [setLogger, [ '@logger' ]]
        tags:
            - { name: monolog.logger, channel: admin_statistics }

    OpenDxp\Bundle\AdminBundle\EventListener\EnablePreviewTimeSliderListener: ~

    #
    # Workflows
    #

    OpenDxp\Bundle\AdminBundle\EventListener\WorkflowManagementListener:
        public: true # can be disabled
