services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # SECURITY
    #

    # standard user provider returning admin users wrapped in a OpenDxp\Bundle\AdminBundle\Security\User\User proxy object.
    # using this user provider allows implementations to authenticate against opendxp users on every desired firewall
    OpenDxp\Bundle\AdminBundle\Security\User\UserProvider:
        public: true

    # the password hasher factory builds a dedicated hasher per user
    # as we need the user instance to hash passwords.
    # we don't specifiy this as fully qualified class name as there can be multiple factories (one for each user type)
    opendxp_admin.security.password_hasher_factory:
        class: OpenDxp\Security\Hasher\Factory\UserAwarePasswordHasherFactory
        arguments:
            - OpenDxp\Bundle\AdminBundle\Security\Hasher\AdminPasswordHasher

    # Authenticators for handling admin login and session authentications
    OpenDxp\Bundle\AdminBundle\Security\Authenticator\AdminTokenAuthenticator:
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: security }

    OpenDxp\Bundle\AdminBundle\Security\Event\LogoutListener:
        tags:
            - { name: 'kernel.event_subscriber', dispatcher: 'security.event_dispatcher.opendxp_admin'}

    OpenDxp\Bundle\AdminBundle\Security\User\TokenStorageUserResolver:
        public: true
        arguments:
            - '@security.token_storage'

    OpenDxp\Bundle\AdminBundle\Security\User\UserLoader: ~

    OpenDxp\Bundle\AdminBundle\Security\CsrfProtectionHandler:
        public: true
        arguments:
            - '%opendxp_admin.csrf_protection.excluded_routes%'
            - '@twig'
        calls:
            - [setLogger, ['@logger']]
        tags:
            - { name: monolog.logger, channel: security }

    OpenDxp\Bundle\AdminBundle\Security\ContentSecurityPolicyHandler:
        public: true
        calls:
            - [ setLogger, [ '@logger' ] ]
        tags:
            - { name: monolog.logger, channel: security }

    # user checker checking admin users for validity
    OpenDxp\Bundle\AdminBundle\Security\User\UserChecker: ~

