parameters:
    secret: ThisTokenIsNotSoSecretChangeIt

services:
    _defaults:
        autowire: true
        autoconfigure: true

    #
    # CONTROLLERS
    #

    # auto-register all controllers as services
    OpenDxp\Bundle\AdminBundle\Controller\:
        resource: '../src/Controller'
        public: true
        tags: ['controller.service_arguments']

    #
    # TRANSLATIONS
    #

    OpenDxp\Bundle\AdminBundle\Translation\AdminUserTranslator: ~

    #
    # GDPR Services
    #

    # Tagged data providers will be injected from compiler pass
    OpenDxp\Bundle\AdminBundle\GDPR\DataProvider\Manager: ~

    # Providers implementing DataProviderInterface will be auto-tagged via autoconfiguration
    OpenDxp\Bundle\AdminBundle\GDPR\DataProvider\DataObjects:
        arguments:
            $config: '%opendxp.gdpr-data-extrator.dataobjects%'

    OpenDxp\Bundle\AdminBundle\GDPR\DataProvider\Assets:
        arguments:
            $config: '%opendxp.gdpr-data-extrator.assets%'

    OpenDxp\Bundle\AdminBundle\GDPR\DataProvider\SentMail: ~
    OpenDxp\Bundle\AdminBundle\GDPR\DataProvider\OpenDxpUsers:
        arguments:
            $logsDir: '%kernel.logs_dir%'


    #
    # Grid Helper Service
    #

    OpenDxp\Bundle\AdminBundle\Helper\GridHelperService: ~


    #
    # Default Preview Generator
    #

    OpenDxp\Model\DataObject\ClassDefinition\PreviewGeneratorInterface:
        class: OpenDxp\Bundle\AdminBundle\Service\PreviewGenerator

    #
    # Twig Extensions
    #

    OpenDxp\Twig\Extension\AdminExtension: ~
    
    OpenDxp\Bundle\AdminBundle\Twig\Extension\AdminExtension: ~

    #
    # Workflows
    #
    
    OpenDxp\Bundle\AdminBundle\Service\Workflow\ActionsButtonService: ~

    #
    # Admin Config Services
    #
    OpenDxp\Bundle\AdminBundle\System\AdminConfig: ~

    #
    # Element Services
    #
    OpenDxp\Bundle\AdminBundle\Service\ElementServiceInterface:
        class: OpenDxp\Bundle\AdminBundle\Service\ElementService
