scheb_two_factor:
    two_factor_condition: OpenDxp\Bundle\AdminBundle\Security\OpenDxpUserTwoFactorCondition
    google:
        enabled: true                                       # If Google Authenticator should be enabled, default false
        server_name: OpenDxp                                # Server name used in QR code
        issuer: OpenDxp                                     # Issuer name used in QR code

    security_tokens:
        - OpenDxp\Bundle\AdminBundle\Security\Authentication\Token\TwoFactorRequiredToken
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken

services:
    _defaults:
        autowire: true
        autoconfigure: true

    OpenDxp\Bundle\AdminBundle\Security\OpenDxpUserTwoFactorCondition: ~
