services:
    _defaults:
        autowire: true
        autoconfigure: true

    # resolvers and operator/value factories will be injected from compiler pass
    # TODO refactor how the service is used and change to private. Currently it is
    # used in a static method fetching the service from the container.
    OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Service:
        public: true

    #TODO: BC Layer, remove with OpenDxp 12
    OpenDxp\DataObject\GridColumnConfig\Service: '@OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Service'

    #
    # OPERATOR FACTORIES
    #

    opendxp.data_object.grid_column_config.operator.factory.anonymizer:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Anonymizer
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: Anonymizer }

    opendxp.data_object.grid_column_config.operator.factory.any_getter:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\AnyGetter
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: AnyGetter }

    opendxp.data_object.grid_column_config.operator.factory.arithmetic:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Arithmetic
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: Arithmetic }

    opendxp.data_object.grid_column_config.operator.factory.asset_metadata_getter:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\AssetMetadataGetter
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: AssetMetadataGetter }

    opendxp.data_object.grid_column_config.operator.factory.base64:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Base64
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: Base64 }

    opendxp.data_object.grid_column_config.operator.factory.boolean:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Boolean
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: Boolean }

    opendxp.data_object.grid_column_config.operator.factory.boolean_formatter:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\BooleanFormatter
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: BooleanFormatter }

    opendxp.data_object.grid_column_config.operator.factory.case_converter:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\CaseConverter
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: CaseConverter }

    opendxp.data_object.grid_column_config.operator.factory.char_counter:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\CharCounter
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: CharCounter }

    opendxp.data_object.grid_column_config.operator.factory.concatenator:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Concatenator
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: Concatenator }

    opendxp.data_object.grid_column_config.operator.factory.date_formatter:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\DateFormatter
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: DateFormatter }

    opendxp.data_object.grid_column_config.operator.factory.element_counter:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\ElementCounter
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: ElementCounter }

    opendxp.data_object.grid_column_config.operator.factory.field_collection_getter:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\FieldCollectionGetter
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: FieldCollectionGetter }

    opendxp.data_object.grid_column_config.operator.factory.is_equal:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\IsEqual
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: IsEqual }

    opendxp.data_object.grid_column_config.operator.factory.iterator:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Iterator
        tags:
        - { name: opendxp.data_object.grid_column_config.operator_factory, id: Iterator }

    opendxp.data_object.grid_column_config.operator.factory.geopoint_renderer:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\GeopointRenderer
        tags:
        - { name: opendxp.data_object.grid_column_config.operator_factory, id: GeopointRenderer }

    opendxp.data_object.grid_column_config.operator.factory.image_renderer:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\ImageRenderer
        tags:
        - { name: opendxp.data_object.grid_column_config.operator_factory, id: ImageRenderer }

    opendxp.data_object.grid_column_config.operator.factory.hotspotimage_renderer:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\HotspotimageRenderer
        tags:
        - { name: opendxp.data_object.grid_column_config.operator_factory, id: HotspotimageRenderer }

    opendxp.data_object.grid_column_config.operator.factory.json:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\JSON
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: JSON }

    opendxp.data_object.grid_column_config.operator.factory.lf_expander:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\LFExpanderFactory
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: LFExpander }

    opendxp.data_object.grid_column_config.operator.factory.locale_switcher:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\LocaleSwitcherFactory
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: LocaleSwitcher }

    opendxp.data_object.grid_column_config.operator.factory.merge:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Merge
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: Merge }

    opendxp.data_object.grid_column_config.operator.factory.object_field_getter:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\ObjectFieldGetter
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: ObjectFieldGetter }

    opendxp.data_object.grid_column_config.operator.factory.php:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\PHP
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: PHP }

    opendxp.data_object.grid_column_config.operator.factory.php_code:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\PHPCode
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: PHPCode }

    opendxp.data_object.grid_column_config.operator.factory.property_getter:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\PropertyGetter
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: PropertyGetter }

    opendxp.data_object.grid_column_config.operator.factory.required_by:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\RequiredBy
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: RequiredBy }

    opendxp.data_object.grid_column_config.operator.factory.string_contains:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\StringContains
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: StringContains }

    opendxp.data_object.grid_column_config.operator.factory.string_replace:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\StringReplace
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: StringReplace }

    opendxp.data_object.grid_column_config.operator.factory.substring:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Substring
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: Substring }

    opendxp.data_object.grid_column_config.operator.factory.text:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Text
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: Text }

    opendxp.data_object.grid_column_config.operator.factory.translate_value:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\TranslateValueFactory
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: TranslateValue }

    opendxp.data_object.grid_column_config.operator.factory.trimmer:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Trimmer
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: Trimmer }

    opendxp.data_object.grid_column_config.operator.factory.alias:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\DefaultOperatorFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Alias
        tags:
            - { name: opendxp.data_object.grid_column_config.operator_factory, id: Alias }

    opendxp.data_object.grid_column_config.operator.factory.workflowstate:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Operator\Factory\WorkflowStateFactory
        tags:
        - { name: opendxp.data_object.grid_column_config.operator_factory, id: WorkflowState }



    #
    # VALUE FACTORIES
    #

    opendxp.data_object.grid_column_config.value.factory.default:
        class: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Value\Factory\DefaultValueFactory
        arguments:
            $className: OpenDxp\Bundle\AdminBundle\DataObject\GridColumnConfig\Value\DefaultValue
        tags:
            - { name: opendxp.data_object.grid_column_config.value_factory, id: DefaultValue }

